# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppChuckNorris' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppChuckNorris

  target 'AppChuckNorrisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppChuckNorrisUITests' do
    # Pods for testing
  end

pod 'Alamofire'

end
